### ISSUE TITLE
Add functionality to view customer details (of the user) and update customer details (of the user)

### ISSUE THREAD

**Issue by longtomjr** [registreerocks/registree-core#29]

**Comment by sabinebertram** [comment]
Which ones are we referring to here? The company details (customerdb) or the personal details (auth0) or both?

**Comment by longtomjr** [comment]
This is to mimic the functionality that we have on the dashboard currently, only to provide the mutations/queries needed in core. I cannot remember if we change anything in Auth0 on the dashboard, or if we do it through a db-api, but if recall correctly everything is done through the customerdb-api.

In this case we should consider moving the functionality of the customerDB-api into core, but when we do, we will just need to make a decision on the persistence layer will use for core, and how we will handle migrating over.

**Comment by sabinebertram** [comment]
Yes, I would love to move it into core. It is only in the customer db api because there was no better place. We should chat about the persistence layer because I'm not sure I understand what we need it for in this scenario.

**Comment by longtomjr** [comment]
@sabinebertram We will need the persistence setup if we want to move the functionality that is in in db-api into core.

**Comment by sabinebertram** [comment]
TODO: set up a call to discuss
