### ISSUE TITLE
Add enum type for the Academic Year Of Study buckets

### ISSUE THREAD

**Issue by longtomjr** [registreerocks/registree-core#355]
- [x] `createQuery`, `expandQuery` and `getQuote` should accept a list of the academic year of study enum instances
- [x] Create a query that returns all of the enum values, as well as user facing metadata.

Deferred:

- ~For `expandQuery` buckets can only be added, and never be removed~ (deferred until we implement the real functionality)

**Comment by PiDelport** [comment]
Discussed with @longtomjr: this PR only has placeholder functionality for `expandQuery`, so we're not going to implement the validation as part of this yet. We'll do this as part of the real functionality for this field.
